DATA EXPLORATION - VANGUARD A/B TEST

IMPORT LIBRARIES

In [1]:
import pandas as pd 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

sns.set_style("whitegrid")

1. LOAD THE DATASETS

In [23]:
data_path = "data/raw_data"
df_demo = pd.read_csv(f"{data_path}/df_final_demo.txt")
df_experiment = pd.read_csv(f"{data_path}/df_final_experiment_clients.txt")
df_web_1 = pd.read_csv(f"{data_path}/df_final_web_data_pt_1.txt")
df_web_2 = pd.read_csv(f"{data_path}/df_final_web_data_pt_2.txt")

web = pd.concat([df_web_1, df_web_2], axis=0)

DATASET: DEMOGRAPHICS

In [ ]:
# Check for duplicates based only on the 'client_id' - no duplicates
print ("Duplicate client_ids:", df_demo.duplicated(subset=['client_id']).sum())

#Unique values for gender variable - unknown category
print ("Gender values:")
print (df_demo["gendr"].value_counts(dropna=False))

Duplicate client_ids: 0
Gender values:
gendr
U    24122
M    23724
F    22745
X        3
Name: count, dtype: int64

In [50]:
#Distribution of clnt_age

print("Distribution of client age:", df_demo["clnt_age"].describe())

Distribution of client age: count    70594.000000
mean        46.442240
std         15.591273
min         13.500000
25%         32.500000
50%         47.000000
75%         59.000000
max         96.000000
Name: clnt_age, dtype: float64

In [8]:
df_demo.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [34]:
df_demo.shape

(70609, 9)

In [37]:
df_demo.isnull().sum()

client_id           0
clnt_tenure_yr      0
clnt_tenure_mnth    0
clnt_age            0
gendr               0
num_accts           0
bal                 0
calls_6_mnth        0
logons_6_mnth       0
dtype: int64

In [36]:
#Drop null values
df_demo = df_demo.dropna()

In [10]:
df_experiment.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [22]:
df_experiment.shape

(70609, 2)

In [ ]:
#In this dataset, there are 20109 missing values, which means this customers need to be dropped out, since they didn't make into the sample
df_experiment.isnull().sum()
df_experiment.nunique()

#Check unique values in the Vatiation column
df_experiment["Variation"].unique()

array(['Test', 'Control', nan], dtype=object)

In [ ]:
#Checking for duplicates - no duplicates found in dataset 
experiment_duplicates = df_experiment.duplicated(subset=['client_id']).sum()
experiment_duplicates

np.int64(0)

In [ ]:
df_web_1.head()
df_web_1.shape

(343141, 5)

In [15]:
df_web_2.head()
df_web_2.shape

(412264, 5)

In [24]:
web.isnull().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [35]:
web.head(10)
web.shape

(755405, 5)