DATA EXPLORATION - VANGUARD A/B TEST

IMPORT LIBRARIES

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

sns.set_style("whitegrid")

1. LOAD THE DATASETS

In [2]:
data_path = "data/raw_data"
df_demo = pd.read_csv(f"{data_path}/df_final_demo.txt")
df_experiment = pd.read_csv(f"{data_path}/df_final_experiment_clients.txt")
df_web_1 = pd.read_csv(f"{data_path}/df_final_web_data_pt_1.txt")
df_web_2 = pd.read_csv(f"{data_path}/df_final_web_data_pt_2.txt")

web = pd.concat([df_web_1, df_web_2], axis=0)

## Phase 1 — EDA & Data Cleaning

DATASET: DEMOGRAPHICS

In [4]:
df_demo.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [5]:
df_demo.dtypes

client_id             int64
clnt_tenure_yr      float64
clnt_tenure_mnth    float64
clnt_age            float64
gendr                object
num_accts           float64
bal                 float64
calls_6_mnth        float64
logons_6_mnth       float64
dtype: object

In [11]:
df_demo.shape

(70609, 9)

In [9]:
df_experiment.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [10]:
df_experiment.shape

(70609, 2)

In [14]:
df_exde = pd.merge(df_demo, df_experiment, on='client_id', how='outer')
df_exde

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,169,21.00,262.00,47.50,M,2.00,501570.72,4.00,4.00,NaN
1,555,3.00,46.00,29.50,U,2.00,25454.66,2.00,6.00,Test
2,647,12.00,151.00,57.50,M,2.00,30525.80,0.00,4.00,Test
3,722,11.00,143.00,59.50,F,2.00,22466.17,1.00,1.00,NaN
4,934,9.00,109.00,51.00,F,2.00,32522.88,0.00,3.00,Test
...,...,...,...,...,...,...,...,...,...,...
70604,9999400,7.00,86.00,28.50,U,2.00,51787.04,0.00,3.00,Test
70605,9999626,9.00,113.00,35.00,M,2.00,36642.88,6.00,9.00,Test
70606,9999729,10.00,124.00,31.00,F,3.00,107059.74,6.00,9.00,Test
70607,9999832,23.00,281.00,49.00,F,2.00,431887.61,1.00,4.00,Test
70608,9999839,13.00,160.00,28.50,F,2.00,67425.35,3.00,3.00,NaN

In [17]:
output_dir = "data/processed"
os.makedirs(output_dir, exist_ok=True)

df_exde.to_csv(f"{output_dir}/df_exde.csv", index=False)

print("Exported:")
for f in os.listdir(output_dir):
    path = os.path.join(output_dir, f)
    size = os.path.getsize(path)
    print(f"  {f} ({size:,} bytes)")

Exported:
  df_exde.csv (3,750,925 bytes)

In [ ]:
pd.set_option('display.float_format', '{:.2f}'.format)
df_exde.describe()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,70609.00,70595.00,70595.00,70594.00,70595.00,70595.00,70595.00,70595.00
mean,5004991.88,12.05,150.66,46.44,2.26,147445.24,3.38,5.57
std,2877277.63,6.87,82.09,15.59,0.53,301508.71,2.24,2.35
min,169.00,2.00,33.00,13.50,1.00,13789.42,0.00,1.00
25%,2519329.00,6.00,82.00,32.50,2.00,37346.83,1.00,4.00
50%,5016978.00,11.00,136.00,47.00,2.00,63332.90,3.00,5.00
75%,7483085.00,16.00,192.00,59.00,2.00,137544.90,6.00,7.00
max,9999839.00,62.00,749.00,96.00,8.00,16320040.15,7.00,9.00

In [22]:
df_exde.isna().sum()

client_id               0
clnt_tenure_yr         14
clnt_tenure_mnth       14
clnt_age               15
gendr                  14
num_accts              14
bal                    14
calls_6_mnth           14
logons_6_mnth          14
Variation           20109
dtype: int64

In [20]:
# Check for duplicates based only on the 'client_id' - no duplicates
print ("Duplicate client_ids:", df_exde.duplicated(subset=['client_id']).sum())

#Unique values for gender variable - unknown category
print ("Gender values:")
print (df_exde["gendr"].value_counts(dropna=False))

Duplicate client_ids: 0
Gender values:
gendr
U      24122
M      23724
F      22746
NaN       14
X          3
Name: count, dtype: int64

In [50]:
#Distribution of clnt_age

print("Distribution of client age:", df_demo["clnt_age"].describe())

Distribution of client age: count    70594.000000
mean        46.442240
std         15.591273
min         13.500000
25%         32.500000
50%         47.000000
75%         59.000000
max         96.000000
Name: clnt_age, dtype: float64

In [8]:
df_demo.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [34]:
df_demo.shape

(70609, 9)

In [37]:
df_demo.isnull().sum()

client_id           0
clnt_tenure_yr      0
clnt_tenure_mnth    0
clnt_age            0
gendr               0
num_accts           0
bal                 0
calls_6_mnth        0
logons_6_mnth       0
dtype: int64

In [36]:
#Drop null values
df_demo = df_demo.dropna()

In [10]:
df_experiment.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

In [22]:
df_experiment.shape

(70609, 2)

In [ ]:
#In this dataset, there are 20109 missing values, which means this customers need to be dropped out, since they didn't make into the sample
df_experiment.isnull().sum()
df_experiment.nunique()

#Check unique values in the Vatiation column
df_experiment["Variation"].unique()

array(['Test', 'Control', nan], dtype=object)

In [ ]:
#Checking for duplicates - no duplicates found in dataset 
experiment_duplicates = df_experiment.duplicated(subset=['client_id']).sum()
experiment_duplicates

np.int64(0)

In [ ]:
df_web_1.head()
df_web_1.shape

(343141, 5)

In [15]:
df_web_2.head()
df_web_2.shape

(412264, 5)

In [24]:
web.isnull().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [35]:
web.head(10)
web.shape

(755405, 5)